### ISSUE TITLE
Aparente error al pasar la contraseña del certificado al módulo java

### ISSUE THREAD

**Issue by otte845** [TIPS-SA/facturacionelectronicapy-xmlsign#12]
Al renovar el certificado este año, ocurre el siguiente error al intentar firmar un XML

La contraseña del certificado tenía el carácter '$', luego de cambiar la contraseña por una sin '$' funciona sin problemas

```
may 24 16:00:35 npm[2662]: Error: Command failed: "/usr/lib/jvm/java-11-openjdk-amd64/bin/java" -Dfile.encoding=IBM850 -classpath "/var/www/FENode/node_modules/facturacionelectronicapy-xmlsign/dist" SignXML "/var/www/FENode/node_modules/facturacionelectronicapy-xmlsign/dist/xml_sign_temp_440200.xml" "cert.p12" "*****" "DE"
may 24 16:00:35 npm[2662]: Exception in thread "main" java.io.IOException: keystore password was incorrect
may 24 16:00:35 npm[2662]:         at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2092)
may 24 16:00:35 npm[2662]:         at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
may 24 16:00:35 npm[2662]:         at java.base/java.security.KeyStore.load(KeyStore.java:1479)
may 24 16:00:35 npm[2662]:         at SignXML.main(SignXML.java:78)
may 24 16:00:35 npm[2662]: Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
```

**Comment by jrgonzalez3** [comment]
Efectivamente, mismo inconveniente.. cuando contiene $ o # , si se escapa firma, pero al enviar falla la clave. 
solo pasa en linux, en windows sin problemas
